name: alpha-mystery
channels:
  - conda-forge
  - anaconda
dependencies:
  - tabulate
  - pandas
  - numpy
  - pip:
          -biopython
          -ete3
          #    -pylexibench
          #    -pythialabelgenerator

